### ISSUE TITLE
Gatsby plugin tinacms is borken?

### ISSUE THREAD

**Issue by dingyi** [tinacms/gatsby-starter-tinacms#1]
It says:

error An unexpected error occurred: "https://registry.yarnpkg.com/@tinacms/gatsby-tinacms-remark/-/gatsby-tinacms-remark-0.3.0.tgz: Request failed \"404 Not Found\"".

when I install this starter.

**Comment by fabianderijk** [comment]
I've got the same issue.

**Comment by mckelveygreg** [comment]
I replaced those packages with the un-namespaced ones documented in the manual setup docs.
https://tinacms.org/docs/gatsby/manual-setup
and the next page
https://tinacms.org/docs/gatsby/markdown
```
    "@tinacms/gatsby-plugin-tinacms": "^0.1.4",
    "@tinacms/gatsby-tinacms-git": "^0.2.1",
    "@tinacms/gatsby-tinacms-remark": "^0.3.0",

```
to
```
    "gatsby-plugin-tinacms": "^0.1.7",
    "gatsby-tinacms-git": "^0.2.4",
    "gatsby-tinacms-remark": "^0.3.4",

```

**Comment by fabianderijk** [comment]
Thanks. I'll try that as well!

**Comment by fabianderijk** [comment]
Ahh cool. I'll try that!




Outlook voor Android downloaden







On Thu, Oct 17, 2019 at 9:06 AM +0200, "Greg McKelvey" <notifications@github.com> wrote:












I replaced those packages with the un-namespaced ones documented in the manual setup docs.

https://tinacms.org/docs/gatsby/manual-setup

and the next page

https://tinacms.org/docs/gatsby/markdown
    "@tinacms/gatsby-plugin-tinacms": "^0.1.4",
    "@tinacms/gatsby-tinacms-git": "^0.2.1",
    "@tinacms/gatsby-tinacms-remark": "^0.3.0",




to
    "gatsby-plugin-tinacms": "^0.1.7",
    "gatsby-tinacms-git": "^0.2.4",
    "gatsby-tinacms-remark": "^0.3.4",

**Comment by c0r5a1r** [comment]
> I replaced those packages with the un-namespaced ones documented in the manual setup docs.
> https://tinacms.org/docs/gatsby/manual-setup
> and the next page
> https://tinacms.org/docs/gatsby/markdown
> 
> ```
>     "@tinacms/gatsby-plugin-tinacms": "^0.1.4",
>     "@tinacms/gatsby-tinacms-git": "^0.2.1",
>     "@tinacms/gatsby-tinacms-remark": "^0.3.0",
> ```
> 
> to
> 
> ```
>     "gatsby-plugin-tinacms": "^0.1.7",
>     "gatsby-tinacms-git": "^0.2.4",
>     "gatsby-tinacms-remark": "^0.3.4",
> ```

It helps me.

**Comment by spbyrne** [comment]
This is fixed with the `remove namespaced @tinacms` PR.

**Comment by ncphillips** [comment]
🤦‍♂️knew I was missed the renaming somewhere. Thanks for the heads up everyone!
