### ISSUE TITLE
I dont see editable fields in Sidebar

### ISSUE THREAD

**Issue by krngd2** [tinacms/gatsby-starter-tinacms#3]
I just installed the started template and started `gatsby develop` 
When i open side bar it just says 

👋
Welcome to Tina!

Let's get a form set up
so you can start editing.

📖 Form Setup Guide

I went through the documentation and setup 
Everything is setup already in the starter, still I don't see any form fields 
Is there any thing I am missing ?

edit:
Checked the console there is an error 
    FAILED TypeError: "expected input to be a string or buffer"
        toString utils.js:42
        exports to-file.js:39
        matter index.js:34
        u index.js:1

**Comment by stonewjr** [comment]
somethings wrong check please

**Comment by doppioslash** [comment]
Same problem. I'm using:
- node 12.13.0
- Gatsby CLI version: 2.8.11
- Gatsby version: 2.15.36
Same problem both on Firefox and Chromium.

**Comment by rickgregory** [comment]
I see this also. More precisely, if I click + in the upper right of the sidebar, I can create a post but only with a title. If I enter a title, then click on the title there are no editable fields. 

There are two issue here, really. One is that I'd expect a start to work, not be half done and this feels like the new content creation code isn't there. Second is that the docs on creating new content at https://tinacms.org/docs/gatsby/markdown#creating-new-markdown-files simply isn't clear. There are no directions on what to with the code at https://tinacms.org/docs/gatsby/markdown#1-creating-content-button-plugins. Do I create a new file to hold this? If so where? Or do I add it to a file? If so, which one? 

If I scroll down to section two it's not clear what to do with the content under the subhead "Example: src/pages/index.js" and in fact text just above that says "NOTE: No changes need to be made to the BlogIndex component itself."

All of this might be intuitively obvious to someone who's very familiar with React, but as someone new to it, clearer docs would be a great help.

**Comment by kendallstrautman** [comment]
Hey all, apologies for the delay in looking into this. It seems all of the Tina packages needed to be updated in the demo. Things should be working now! Feel free to reopen the issue you have more trouble.

**Comment by DirtyF** [comment]
yay, sorry folks, we forgot to update Tina packages on the starter on last release, we'll be more careful next time.
